### ISSUE TITLE
Avoid kernel restart if already installed?

### ISSUE THREAD

**Issue by tonigi** [jaimergp/condacolab#1]
Would it make sense to avoid restarting the kernel when running `condacolab.install()` on an already-installed state ? This would make it re-executing all cells a worry-less (idempotent if you want) action.

(Probably the same behaviour can be achieved without code changes by wrapping install in a "if ...check" call).

**Comment by jaimergp** [comment]
Oh, sure, that's a good point. We can inject a canary variable or file to test whether the installation was run or not (and check it works). Thanks!

**Comment by jaimergp** [comment]
Submitted PR #2 

Can you test with this snippet?

```
!wget -q https://raw.githubusercontent.com/jaimergp/condacolab/run_checks/condacolab.py
import condacolab
condacolab.install()
```

It works for me :)

**Comment by tonigi** [comment]
It seems to "just work", which is great! Thanks for this project!

**Comment by jaimergp** [comment]
Nice! I'll cut a 0.1.1 release later then. Thanks again for the report!

**Comment by jaimergp** [comment]
Available in PyPI: https://pypi.org/project/condacolab/0.1.1/
