### ISSUE TITLE
Conda not installing package for Python 3.9, getting package for Python 3.8 instead

### ISSUE THREAD

**Issue by AlbertoCasasOrtiz** [jaimergp/condacolab#51]
I am installing condacolab:

```
!pip install -q condacolab
import condacolab
condacolab.install()
```

And then installing my package:

```
!conda install -c opensim_admin opensim
```

But the version installed by conda is for Python 3.8.

```
opensim-4.4 | py38np120
```

`python --version` returns `Python 3.9.16`, and `!conda info` returns `python version : 3.9.16.final.0`. Also, I can confirm that the package for Python 3.9 exists because when I install it specifying the version and tag, it install the proper package:

```
conda install -c opensim_admin opensim=4.4=py39np120
```

This installs the correct version `opensim-4.4 | py39np120` and my code works.

Could it be that condacolab / conda is not retrieving the correct packages?

**Comment by jaimergp** [comment]
Hi @AlbertoCasasOrtiz, can you share a notebook with the problem reproducer so I can take a look? Thanks 🙏

**Comment by AlbertoCasasOrtiz** [comment]
Sure! Here there is a notebook with this problem:

https://colab.research.google.com/drive/1rKO-4HTl3Y6voafSESE22Guxev0bQLlT?usp=sharing

Thank you.

**Comment by jaimergp** [comment]
I can reproduce locally, without `condacolab` and outside Colab, so this is not a problem with `condacolab` itself.

That said, I can explain why you are seeing this issue. While the latest builds of `opensim` are  correctly restricting `python`'s version, there's a previous version with an open `python` dependency:

<img width="815" alt="image" src="https://user-images.githubusercontent.com/2559438/229291038-23396012-fe05-48f8-a83d-efa3c25b0551.png">

---

`mamba` does exhibit the behaviour you want, and is included in the default installation, so feel free to use it instead:

```
!mamba install -c opensim-org opensim
```

The other alternative is to restrict `opensim` to a `py39` build explicitly: `conda install -c opensim-org 'opensim=*=*py39*'`.

The last option is to rebuild the offending packages (underspecified `python` constraints) and remove the `main` label from the old ones. 


This is the one being selected.

**Comment by AlbertoCasasOrtiz** [comment]
**Thank you** for investigating this @jaimergp, we will try to fix the package on our side and use mamba instead until we fix it.

I am closing this issue. Thanks again!
