### ISSUE TITLE
Python 3.10

### ISSUE THREAD

**Issue by sokrypton** [jaimergp/condacolab#55]
Is there support for python 3.10 (this is now the default).

I was looking at the GitHub for mamba, looks like
 that's only supported for 3.9

**Comment by sokrypton** [comment]
maybe it's ok, but I noticed this shows 3.9
https://github.com/jaimergp/miniforge/releases/

**Comment by jaimergp** [comment]
With Colab catching up with Python versions, we can use the official miniforge releases, no need for the Colab-custom fork.
