### ISSUE TITLE
PackagesNotFoundError: The following packages are missing from the target environment:   - cudatoolkit=12.2

### ISSUE THREAD

**Issue by emilioangelina** [jaimergp/condacolab#61]
Aparently, cudatoolkit has been recently updated to a newer version 12.2 at colab and this generated conflcts when trying to install packages like openmm and ambertools with conda. 

When I execute the following cell in colab: 

!conda install openmmforcefields -c conda-forge -y
!conda install -c conda-forge ambertools -y
!conda install -c conda-forge parmed -y

I throws the following error: 

PackagesNotFoundError: The following packages are missing from the target environment:
  - cudatoolkit=12.2

ModuleNotFoundError                       Traceback (most recent call last)
[<ipython-input-2-26f4587fd5f2>](https://localhost:8080/#) in <cell line: 12>()
     10 
     11 #load dependencies
---> 12 from openmm import app, unit
     13 from openmm.app import HBonds, NoCutoff, PDBFile
     14 from openff.toolkit.topology import Molecule, Topology

ModuleNotFoundError: No module named 'openmm'

**Comment by kimjc95** [comment]
Try [this](https://github.com/conda-incubator/condacolab/issues/60#issuecomment-1858067919) and let me know if this resolves the issue.

**Comment by emilioangelina** [comment]
It worked!!, thanks a lot

**Comment by jaimergp** [comment]
Thanks for the report! Closing as duplicate. See comment in https://github.com/conda-incubator/condacolab/issues/60#issuecomment-1859867325 for a potential solution!
